# Process Hackathons

In [4]:
import pandas as pd
import pathlib
import requests
from tqdm.asyncio import tqdm
import re

In [5]:
data_root = pathlib.Path("../data")
output_root = data_root / pathlib.Path("outputs")
output_files = output_root.glob("project-output*.csv")

df = None
for file in output_files:
    df_partial = pd.read_csv(file)
    if df is None:
        df = df_partial
    else:
        df = pd.concat([df, df_partial], ignore_index=True)

df.head()

,title,description,built-with,is-winner,full-description,hackathon_id
0,NaN,NaN,"twitter,android",False,\n \n Viewing Tweets without their usern...,936
1,NaN,NaN,weebly,False,\n \n https://docs.google.com/presentati...,2401
2,NaN,NaN,NaN,False,\n \n Jewish learning has traditionally ...,2401
3,NaN,NaN,NaN,False,\n \n Inspiration \n\n Elementary school...,2401
4,NaN,NaN,"html,webgl,javascript,web",False,\n \n We like pictures and so originally...,1606

In [6]:
def clean_description(description: str):
    if not isinstance(description, str):
        return ""

    text = str(description).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["description"] = df["description"].apply(clean_description)
df["full-description"] = df["full-description"].apply(clean_description)
df.head()

,title,description,built-with,is-winner,full-description,hackathon_id
0,NaN,,"twitter,android",False,viewing tweets without their username or infor...,936
1,NaN,,weebly,False,,2401
2,NaN,,NaN,False,jewish learning has traditionally been done in...,2401
3,NaN,,NaN,False,inspiration elementary school students receive...,2401
4,NaN,,"html,webgl,javascript,web",False,we like pictures and so originally we wanted t...,1606

In [7]:
df.to_csv(data_root / "projects.csv", index=False)

# Process Hackathons

In [8]:
hackathon_df = pd.read_csv(data_root / "hackathons.csv")
hackathon_df.head()

,id,title,url,submission_period_dates,themes,registrations_count
0,27498,AETHRA GLOBAL VIBEATHON 2025,https://aethra-global-vibeathon-2025.devpost.com/,"Nov 14 - Dec 31, 2025","[{'id': 23, 'name': 'Beginner Friendly'}, {'id...",264
1,16954,Winter MelonJam 2025,https://wmj2025.devpost.com/,"Dec 26 - 29, 2025","[{'id': 23, 'name': 'Beginner Friendly'}, {'id...",49
2,27408,Digital Innovation Challenge 2025 - Finance Track,https://dic-2025-finance-track.devpost.com/,"Nov 20 - Dec 29, 2025","[{'id': 3, 'name': 'Fintech'}, {'id': 6, 'name...",176
3,27220,Artificathon 2025,https://artificathon-2025.devpost.com/,"Dec 01 - 28, 2025","[{'id': 19, 'name': 'Education'}, {'id': 6, 'n...",56
4,27377,Square Hacks- Build for Rural India,https://squarehacks.devpost.com/,"Dec 26 - 27, 2025","[{'id': 19, 'name': 'Education'}, {'id': 6, 'n...",472

In [ ]:
from datetime import datetime

def parse_submission_dates(submission_period_dates: str) -> tuple[datetime | None, datetime | None]:
    if submission_period_dates is None or not isinstance(submission_period_dates, str):
        return None, None

    input_length = len(submission_period_dates)
    if input_length == len("Dec 26, 2025"):
        start_time = datetime.strptime(submission_period_dates, "%b %d, %Y")
        end_time = start_time

    elif input_length == len("Dec 26 - 29, 2025"):
        month = submission_period_dates[:3]
        start_date = submission_period_dates[4:6]
        end_date = submission_period_dates[9:11]
        year = submission_period_dates[-4:]

        start_time = datetime.strptime(f"{month} {start_date}, {year}", "%b %d, %Y")
        end_time = datetime.strptime(f"{month} {end_date}, {year}", "%b %d, %Y")

    elif input_length == len("Nov 20 - Dec 29, 2025"):
        start_date = submission_period_dates.split(" - ")[0]
        end_date = submission_period_dates.split(" - ")[1].split(",")[0]
        year = submission_period_dates[-4:]

        start_time = datetime.strptime(f"{start_date}, {year}", "%b %d, %Y")
        end_time = datetime.strptime(f"{end_date}, {year}", "%b %d, %Y")

    elif input_length == len("Dec 04, 2024 - Jan 24, 2025"):
        start_full_date, end_full_date = submission_period_dates.split(" - ")

        start_time = datetime.strptime(start_full_date, "%b %d, %Y")
        end_time = datetime.strptime(end_full_date, "%b %d, %Y")

    else:
        raise ValueError(f"Unexpected submission period dates {submission_period_dates}")

    return start_time, end_time

# Sanity check
accepted_start = datetime(2008, 11, 1)
accepted_end = datetime(2026, 12, 31)
for idx, row in hackathon_df.iterrows():
    parsed_start, parsed_end = parse_submission_dates(row["submission_period_dates"])
    assert accepted_start <= parsed_start <= parsed_end <= accepted_end

In [ ]:
hackathon_df[["submission_start", "submission_end"]] = (
    hackathon_df["submission_period_dates"]
    .apply(parse_submission_dates)
    .apply(pd.Series)
)

hackathon_df.head()

## Add coordinates

In [9]:
geo_location_df = pd.read_csv(data_root / "locations.csv")

In [10]:
hackathon_df_with_locations = pd.merge(hackathon_df, geo_location_df, on="id", how="left")
hackathon_df_with_locations.head()

,id,title,url,submission_period_dates,themes,registrations_count,geo_location
0,27498,AETHRA GLOBAL VIBEATHON 2025,https://aethra-global-vibeathon-2025.devpost.com/,"Nov 14 - Dec 31, 2025","[{'id': 23, 'name': 'Beginner Friendly'}, {'id...",264,Online
1,16954,Winter MelonJam 2025,https://wmj2025.devpost.com/,"Dec 26 - 29, 2025","[{'id': 23, 'name': 'Beginner Friendly'}, {'id...",49,Online
2,27408,Digital Innovation Challenge 2025 - Finance Track,https://dic-2025-finance-track.devpost.com/,"Nov 20 - Dec 29, 2025","[{'id': 3, 'name': 'Fintech'}, {'id': 6, 'name...",176,Online
3,27220,Artificathon 2025,https://artificathon-2025.devpost.com/,"Dec 01 - 28, 2025","[{'id': 19, 'name': 'Education'}, {'id': 6, 'n...",56,Online
4,27377,Square Hacks- Build for Rural India,https://squarehacks.devpost.com/,"Dec 26 - 27, 2025","[{'id': 19, 'name': 'Education'}, {'id': 6, 'n...",472,"IIT Delhi, Indian Institute of Technology Delh..."

In [16]:
from urllib.parse import quote
from dotenv import load_dotenv
import os
load_dotenv()
api_key = os.getenv("GOOGLE_MAPS_API_KEY")

In [17]:
def get_geo_code(geo_location: str):
    if not isinstance(geo_location, str) or geo_location == "Online":
        return None, None

    try:
        request = "https://maps.googleapis.com/maps/api/geocode/json?address={}&key={}".format(
            quote(geo_location), api_key
        )
        response = requests.get(request)
        response.raise_for_status()
        data = response.json()

        result_obj = data["results"][0]

        admin_area_level1 = None
        country_short_name = None
        country_long_name = None
        for component in result_obj.get("address_components", []):
            if "administrative_area_level_1" in component.get("types", []):
                admin_area_level1 = component.get("long_name")
            if "country" in component.get("types", []):
                country_short_name = component.get("short_name")
                country_long_name = component.get("long_name")

        if admin_area_level1 is not None and country_short_name is not None:
            locality = f"{admin_area_level1}, {country_short_name}"
        elif admin_area_level1 is None and country_short_name is not None:
            locality = country_long_name
        elif country_short_name is None and admin_area_level1 is not None:
            locality = admin_area_level1
        else:
            return None, None

        location_dict = result_obj["geometry"]["location"]
        return (location_dict["lat"], location_dict["lng"]), locality

    except Exception as e:
        print(e)
        return None, None

get_geo_code("IIT Delhi, Indian Institute of Technology Delhi, Hauz Khas, New Delhi, Delhi 110016, India")

((28.5410732, 77.1990842), 'Delhi, IN')

In [18]:
coordinate_arr = []
locality_arr = []
for _, row in tqdm(hackathon_df_with_locations.iterrows(), total=len(hackathon_df_with_locations)):
    coordinate, locality = get_geo_code(row["geo_location"])

    coordinate_arr.append(coordinate)
    locality_arr.append(locality)

hackathon_df_with_coordinates = hackathon_df_with_locations.copy()
hackathon_df_with_coordinates["coordinate"] = coordinate_arr
hackathon_df_with_coordinates["locality"] = locality_arr
hackathon_df_with_coordinates.head()

  0%|          | 34/8688 [00:03<10:29, 13.75it/s]

list index out of range

  1%|▏         | 123/8688 [00:08<09:04, 15.72it/s]

list index out of range

  6%|▌         | 508/8688 [00:46<07:22, 18.48it/s]

list index out of range

  6%|▋         | 561/8688 [00:50<08:09, 16.60it/s]

list index out of range

  7%|▋         | 640/8688 [00:54<07:22, 18.18it/s]

list index out of range

  9%|▉         | 824/8688 [01:05<09:07, 14.36it/s]

list index out of range

 10%|▉         | 826/8688 [01:05<12:35, 10.41it/s]

list index out of range

 10%|▉         | 839/8688 [01:07<20:28,  6.39it/s]

list index out of range

 10%|█         | 904/8688 [01:15<20:28,  6.34it/s]

list index out of range

 11%|█         | 956/8688 [01:21<15:34,  8.27it/s]

list index out of range

 18%|█▊        | 1579/8688 [02:13<08:17, 14.30it/s]

list index out of range

 19%|█▉        | 1675/8688 [02:19<07:49, 14.92it/s]

list index out of range

 20%|█▉        | 1703/8688 [02:21<06:47, 17.12it/s]

list index out of range

 25%|██▌       | 2203/8688 [02:50<05:57, 18.12it/s]

list index out of range

 27%|██▋       | 2344/8688 [03:03<08:07, 13.00it/s]

list index out of range

 28%|██▊       | 2392/8688 [03:07<11:19,  9.26it/s]

list index out of range

 30%|██▉       | 2596/8688 [03:22<09:15, 10.98it/s]

list index out of range

 33%|███▎      | 2909/8688 [03:40<05:58, 16.14it/s]

list index out of range

 34%|███▎      | 2914/8688 [03:40<06:56, 13.87it/s]

list index out of range

 36%|███▌      | 3140/8688 [03:58<10:23,  8.90it/s]

list index out of range
list index out of range

 39%|███▉      | 3382/8688 [04:13<04:06, 21.57it/s]

list index out of range

 39%|███▉      | 3420/8688 [04:16<06:34, 13.36it/s]

list index out of range

 41%|████      | 3562/8688 [04:28<05:27, 15.67it/s]

list index out of range

 42%|████▏     | 3672/8688 [04:35<02:33, 32.64it/s]

list index out of range

 43%|████▎     | 3708/8688 [04:36<01:50, 45.01it/s]

list index out of range

 46%|████▌     | 3976/8688 [04:44<03:02, 25.86it/s]

list index out of range

 50%|████▉     | 4330/8688 [04:53<00:53, 82.16it/s]

list index out of range

 53%|█████▎    | 4624/8688 [04:58<00:33, 122.36it/s]

list index out of range

 59%|█████▉    | 5108/8688 [05:00<00:10, 342.60it/s]

list index out of range

 61%|██████    | 5258/8688 [05:02<00:34, 98.12it/s]

list index out of range

 65%|██████▌   | 5679/8688 [05:07<00:39, 77.02it/s]

list index out of range

 66%|██████▌   | 5698/8688 [05:07<00:50, 59.79it/s]

list index out of range

 66%|██████▌   | 5706/8688 [05:08<01:20, 37.18it/s]

list index out of range

 67%|██████▋   | 5820/8688 [05:11<01:03, 44.97it/s]

list index out of range
list index out of range

 69%|██████▉   | 6005/8688 [05:32<04:15, 10.49it/s]

list index out of range

 76%|███████▌  | 6591/8688 [06:45<04:45,  7.35it/s]

list index out of range

 76%|███████▌  | 6599/8688 [06:46<05:09,  6.75it/s]

list index out of range

 76%|███████▋  | 6640/8688 [06:51<02:56, 11.60it/s]

list index out of range

 78%|███████▊  | 6766/8688 [07:06<02:48, 11.42it/s]

list index out of range

 78%|███████▊  | 6793/8688 [07:09<03:56,  8.03it/s]

list index out of range

 79%|███████▉  | 6867/8688 [07:17<02:52, 10.57it/s]

list index out of range

 79%|███████▉  | 6898/8688 [07:20<02:27, 12.18it/s]

list index out of range

 80%|███████▉  | 6944/8688 [07:26<04:07,  7.04it/s]

list index out of range

 80%|████████  | 6972/8688 [07:29<02:51, 10.03it/s]

list index out of range

 80%|████████  | 6987/8688 [07:31<02:55,  9.72it/s]

list index out of range

 81%|████████  | 7053/8688 [07:38<02:32, 10.72it/s]

list index out of range

 81%|████████▏ | 7065/8688 [07:40<02:23, 11.29it/s]

list index out of range

 81%|████████▏ | 7076/8688 [07:41<02:18, 11.66it/s]

list index out of range

 82%|████████▏ | 7128/8688 [07:47<03:06,  8.38it/s]

list index out of range

 82%|████████▏ | 7167/8688 [07:51<03:14,  7.81it/s]

list index out of range

 83%|████████▎ | 7184/8688 [07:53<02:18, 10.85it/s]

list index out of range

 84%|████████▍ | 7321/8688 [08:10<02:41,  8.48it/s]

list index out of range

 85%|████████▌ | 7409/8688 [08:19<02:33,  8.34it/s]

list index out of range

 85%|████████▌ | 7416/8688 [08:20<02:12,  9.62it/s]

list index out of range

 86%|████████▌ | 7469/8688 [08:27<01:42, 11.88it/s]

list index out of range

 86%|████████▋ | 7495/8688 [08:30<02:13,  8.95it/s]

list index out of range

 87%|████████▋ | 7545/8688 [08:35<01:45, 10.86it/s]

list index out of range
list index out of range

 87%|████████▋ | 7551/8688 [08:36<02:10,  8.68it/s]

list index out of range

 88%|████████▊ | 7607/8688 [08:44<02:15,  8.00it/s]

list index out of range

 88%|████████▊ | 7635/8688 [08:47<02:20,  7.51it/s]

list index out of range

 88%|████████▊ | 7666/8688 [08:51<01:49,  9.35it/s]

list index out of range

 89%|████████▉ | 7737/8688 [08:58<01:35,  9.99it/s]

list index out of range

 89%|████████▉ | 7760/8688 [09:01<01:32,  9.98it/s]

list index out of range

 91%|█████████ | 7880/8688 [09:14<01:31,  8.81it/s]

list index out of range

 91%|█████████ | 7915/8688 [09:18<01:08, 11.24it/s]

list index out of range

 92%|█████████▏| 7984/8688 [09:26<00:51, 13.61it/s]

list index out of range

 94%|█████████▎| 8129/8688 [09:42<01:04,  8.66it/s]

list index out of range

 94%|█████████▎| 8139/8688 [09:43<00:44, 12.22it/s]

list index out of range

 94%|█████████▍| 8146/8688 [09:44<00:44, 12.07it/s]

list index out of range

 94%|█████████▍| 8166/8688 [09:46<00:35, 14.51it/s]

list index out of range

 94%|█████████▍| 8186/8688 [09:48<00:31, 15.99it/s]

list index out of range

 94%|█████████▍| 8189/8688 [09:48<00:45, 11.04it/s]

list index out of range
list index out of range

 94%|█████████▍| 8201/8688 [09:50<01:20,  6.07it/s]

list index out of range

 94%|█████████▍| 8203/8688 [09:50<01:20,  6.00it/s]

list index out of range

 94%|█████████▍| 8208/8688 [09:51<01:07,  7.11it/s]

list index out of range

 95%|█████████▍| 8211/8688 [09:51<01:09,  6.83it/s]

list index out of range
list index out of range

 95%|█████████▍| 8216/8688 [09:52<01:00,  7.86it/s]

list index out of range
list index out of range

 95%|█████████▍| 8219/8688 [09:52<01:07,  6.99it/s]

list index out of range

 95%|█████████▍| 8228/8688 [09:53<00:39, 11.57it/s]

list index out of range

 95%|█████████▍| 8251/8688 [09:57<01:10,  6.23it/s]

list index out of range

 95%|█████████▌| 8277/8688 [10:02<01:18,  5.26it/s]

list index out of range

 96%|█████████▌| 8307/8688 [10:06<00:41,  9.21it/s]

list index out of range

 96%|█████████▌| 8333/8688 [10:09<00:48,  7.27it/s]

list index out of range

 96%|█████████▌| 8339/8688 [10:10<00:40,  8.67it/s]

list index out of range

 96%|█████████▌| 8345/8688 [10:11<00:45,  7.49it/s]

list index out of range

 97%|█████████▋| 8444/8688 [10:22<00:32,  7.43it/s]

list index out of range

 97%|█████████▋| 8451/8688 [10:23<00:27,  8.66it/s]

list index out of range

 98%|█████████▊| 8474/8688 [10:26<00:27,  7.91it/s]

list index out of range

 98%|█████████▊| 8509/8688 [10:29<00:15, 11.60it/s]

list index out of range

 98%|█████████▊| 8523/8688 [10:30<00:12, 13.42it/s]

list index out of range

 98%|█████████▊| 8527/8688 [10:31<00:15, 10.64it/s]

list index out of range

100%|██████████| 8688/8688 [10:40<00:00, 13.56it/s]

,id,title,url,submission_period_dates,themes,registrations_count,geo_location,coordinate,locality
0,27498,AETHRA GLOBAL VIBEATHON 2025,https://aethra-global-vibeathon-2025.devpost.com/,"Nov 14 - Dec 31, 2025","[{'id': 23, 'name': 'Beginner Friendly'}, {'id...",264,Online,None,NaN
1,16954,Winter MelonJam 2025,https://wmj2025.devpost.com/,"Dec 26 - 29, 2025","[{'id': 23, 'name': 'Beginner Friendly'}, {'id...",49,Online,None,NaN
2,27408,Digital Innovation Challenge 2025 - Finance Track,https://dic-2025-finance-track.devpost.com/,"Nov 20 - Dec 29, 2025","[{'id': 3, 'name': 'Fintech'}, {'id': 6, 'name...",176,Online,None,NaN
3,27220,Artificathon 2025,https://artificathon-2025.devpost.com/,"Dec 01 - 28, 2025","[{'id': 19, 'name': 'Education'}, {'id': 6, 'n...",56,Online,None,NaN
4,27377,Square Hacks- Build for Rural India,https://squarehacks.devpost.com/,"Dec 26 - 27, 2025","[{'id': 19, 'name': 'Education'}, {'id': 6, 'n...",472,"IIT Delhi, Indian Institute of Technology Delh...","(28.5410732, 77.1990842)","Delhi, IN"

In [19]:
hackathon_df_with_coordinates.to_csv(data_root / "processed_hackathons.csv", index=False)